### PR TITLE
Updated Sub-division data of Brazil, Romania, Kuwait & Bhutan

### LINKED ISSUE #42: Addition of Sub-division data of Brazil, Romania, Kuwait & Bhutan.
Hi, I want to add the Sub-division data of Brazil, Romania, Kuwait & Bhutan.
Can I go ahead ?

### PR DESCRIPTION
**Pull request by Antiquely3059**
Hi, I have added the Sub-division data of Brazil, Romania, Kuwait & Bhutan
source - (for kuwait) https://www.iso.org/obp/ui/#iso:code:3166:KW
(for brazil) https://www.iso.org/obp/ui/#iso:code:3166:BR
(for bhutan) https://www.iso.org/obp/ui/#iso:code:3166:BT
(for romania) https://www.iso.org/obp/ui/#iso:code:3166:RO
closes #42

### CODE REVIEW

**Comment by animator** [comment]
Kuwait sub-division names are not matching the source. From where have you obtained the english names?

**Comment by Antiquely3059** [comment]
I had got the names from Wikipedia, but now I have updated the data as per the source.

**Comment by animator** [comment]
The english names are actually preferred. I was asking because you did not add the source for english names.

**Comment by Antiquely3059** [comment]
I apologise for my mistake.
I have resolved all the errors.
Source for the English names -
https://en.m.wikipedia.org/wiki/Governorates_of_Kuwait
https://kemlu.go.id/kuwaitcity/en/pages/profil_negara_kuwait/1585/etc-menu#:~:text=Kuwait%20has%206%20Governorates%20or,%2C%20Ahmadi%2C%20Farwaniya%20and%20Jahra.&text=According%20to%20the%20data%20in,June%202022%2C

**Comment by ashitaprasad** [comment]
Romania is incorrect.
Closing this PR. It will be better if you raise separate PR for each country.

**Pull request closed without merging**
